name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'task-**'
      - main

jobs:
  jest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: npm ci --legacy-peer-deps

      - name: Test
        run: npm run test:unit
